folio-org/mod-ebsconet

- pom.xml
- src/main/resources/swagger.api/ebsconet.yaml
- src/main/resources/swagger.api/examples/ebsconet_order_line.sample
- src/main/resources/swagger.api/schemas/ebsconet_order_line.json
- src/main/resources/swagger.api/schemas/order_line_number.json
- src/main/resources/swagger.api/schemas/uuid.json
> [MODEBSNET-2] Add swagger configuration and samples.

- pom.xml
- src/main/resources/swagger.api/ebsconet.yaml
> [MODEBSNET-2] Change API path to /orders/order-lines/{poLineNumber}

- src/main/resources/application.yaml
- src/main/resources/db/changelog/changelog-master.xml
> [MODEBSNET-1] Make configuration changes for the deployment.

- descriptors/DeploymentDescriptor-template.json
- pom.xml
- src/main/java/org/folio/ebsconet/ModEbscoNetApplication.java
- src/main/java/org/folio/ebsconet/config/ModEbsconetSpringConfiguration.java
- src/main/java/org/folio/ebsconet/controller/OrdersController.java
- src/main/java/org/folio/ebsconet/controller/TenantController.java
- src/main/resources/application.yaml
- src/main/resources/swagger.api/ebsconet.yaml
> Refator to met deployment requirements

- Jenkinsfile
> Fix Jenkins

- pom.xml
- src/main/java/org/folio/ebsconet/controller/OrdersController.java
- src/main/resources/application.yaml
> [MODEBSNET-7]Fix NPE. Minor refactoring. 

- descriptors/ModuleDescriptor-template.json
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com>
While it's helpful for …
> MODEBSNET-4 Implement update ebsconet order line logic

- pom.xml
https://issues.folio.org/browse/MODEBSNET-8
* updated spring boot starter version
* updated open api generator version
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> MODEBSNET-8 Update spring-boot-starter-parent

- run-env.sh
> MODEBSNET-9 delete kafka option

- NEWS.md
- README.md
- pom.xml
Pre release of mod-ebsconet for 0.1.0
> MODEBSNET-12 MODEBSNET(mod-ebsconet) pre-release - v0.1.0

- NEWS.md
- pom.xml
* https://issues.folio.org/browse/MODEBSNET-11
* updated release notes
While it's helpful …
> MODEBSNET-11 release 1.0.0

- pom.xml
- src/main/java/org/folio/ebsconet/controller/OrdersController.java
- src/main/java/org/folio/ebsconet/controller/ValidationsController.java
- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
- src/main/java/org/folio/ebsconet/service/OrdersService.java
- src/main/resources/application.yaml
- src/main/resources/swagger.api/schemas/mod-orders/source.json
- src/test/java/org/folio/ebsconet/OrdersControllerTest.java
- src/test/java/org/folio/ebsconet/OrdersServiceTest.java
- src/test/resources/mockdata/order_line.json
https://issues.folio.org/browse/MODEBSNET-10
* added mixed orders processing
While it's …
> MODEBSNET-10 Handling mixed orders for ebsconet

- src/main/resources/swagger.api/schemas/mod-orders/composite_po_line.json
https://issues.folio.org/browse/MODORDSTOR-237
* updated schema
- Are the JIRAs under active development?  
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  
While it's helpful for …
> MODORDSTOR-237 pointed acq-models to the latest commit

- pom.xml
- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
- src/test/java/org/folio/ebsconet/OrdersServiceTest.java
- src/test/resources/mockdata/ebsconet_order_line.json
- src/test/resources/mockdata/order_line.json
https://issues.folio.org/browse/MODEBSNET-18
* updated calculations according to story description
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> MODEBSNET-18 Allow EBSCONET to update order with multiple locations

- pom.xml
…penapi-generator
https://issues.folio.org/browse/MODEBSNET-20 > mod-ebsconet: folio-spring-base v2 update
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> [MODEBSNET-20]folio-spring-base v2 update

- descriptors/ModuleDescriptor-template.json
Increase major API versions for:
- order-lines from 2.0 to 3.0
- orders from 11.0 to 12.0 …
> [MODORDSTOR-256] - Major API versions have been increased

- src/main/resources/swagger.api/schemas/mod-orders/composite_po_line.json
https://issues.folio.org/browse/MODORDSTOR-267 …
> MODORDSTOR-267. Rename collection field name for Acquisition method сollection

- src/main/resources/swagger.api/schemas/mod-orders/composite_po_line.json
https://issues.folio.org/browse/MODORDSTOR-266
Update schemas with new field
While it's …
> MODORDSTOR-266 - added automaticExport to poline schemes

- pom.xml
https://issues.folio.org/browse/MODEBSNET-23 …
> MODEBSNET-23. Kiwi R3 2021 - Log4j vulnerability verification and correction

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODEBSNET-26 …
> MODEBSNET-26. Kiwi Hotfix 1.1.1

- pom.xml
https://issues.folio.org/browse/MODEBSNET-24 …
> MODEBSNET-24. Juniper R2 2021 - Log4j vulnerability verification and correction

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODEBSNET-25 …
> MODEBSNET-25. Juniper R2 2021 HF #5 module release

- .gitignore
- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/ebsconet/client/FinanceClient.java
- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
- src/main/java/org/folio/ebsconet/models/MappingDataHolder.java
- src/main/java/org/folio/ebsconet/service/OrdersService.java
- src/main/resources/swagger.api/ebsconet.yaml
- src/main/resources/swagger.api/schemas/mod-finance/expense_class.json
- src/main/resources/swagger.api/schemas/mod-finance/expense_class_collection.json
- src/test/java/org/folio/ebsconet/OrdersServiceTest.java
https://issues.folio.org/browse/MODEBSNET-13
* added fund expense classes support
While it's …
> MODEBSNET-13 added fund expense classes support

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/ebsconet/client/NoteLinksClient.java
- src/main/java/org/folio/ebsconet/client/NoteTypeClient.java
- src/main/java/org/folio/ebsconet/client/NotesClient.java
- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
- src/main/java/org/folio/ebsconet/service/NotesService.java
- src/main/java/org/folio/ebsconet/service/OrdersService.java
- src/main/resources/swagger.api/ebsconet.yaml
- src/main/resources/swagger.api/schemas/mod-notes/link.json
- src/main/resources/swagger.api/schemas/mod-notes/note.json
- src/main/resources/swagger.api/schemas/mod-notes/note_collection.json
- src/test/java/org/folio/ebsconet/OrdersServiceTest.java
- src/test/java/org/folio/ebsconet/TestBase.java
- src/test/java/org/folio/ebsconet/TestSuite.java
- src/test/java/org/folio/ebsconet/service/NotesServiceTest.java
- src/test/resources/mockdata/note-types.json
- src/test/resources/mockdata/notes.json
* https://issues.folio.org/browse/MODEBSNET-27
* Update logic for supporting "customer note" from EBSCONET
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> MODEBSNET-27 Update logic for supporting "customer note" from EBSCONET

- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
- src/main/java/org/folio/ebsconet/service/OrdersService.java
- src/main/resources/swagger.api/schemas/mod-ebsconet/ebsconet_order_line.json
- src/main/resources/swagger.api/schemas/mod-orders/composite_po_line.json
- src/main/resources/swagger.api/schemas/mod-orders/po_line.json
- src/test/java/org/folio/ebsconet/OrdersServiceTest.java
* https://issues.folio.org/browse/MODEBSNET-30
* implemented renewalNote mapping
While it's …
> MODEBSNET-30 Update logic for supporting "Renewal note" from EBSCONET

- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
* https://issues.folio.org/browse/MODEBSNET-27
* removed unnecessary mapping
While it's …
> MODEBSNET-27 removed unnecessary mapping

- src/main/java/org/folio/ebsconet/service/NotesService.java
- src/main/resources/swagger.api/schemas/mod-ebsconet/ebsconet_order_line.json
- src/test/java/org/folio/ebsconet/service/NotesServiceTest.java
> [MODEBSNET-33]- Added customerNote in schema.

- pom.xml
- src/main/java/org/folio/ebsconet/error/DefaultErrorHandler.java
- src/main/java/org/folio/ebsconet/error/UnprocessableEntity.java
- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
- src/main/resources/swagger.api/schemas/mod-ebsconet/ebsconet_order_line.json
- src/test/java/org/folio/ebsconet/OrdersServiceTest.java
[MODEBSNET-22](https://issues.folio.org/browse/MODEBSNET-22) - Support canceling POL(s) through EBSCONET integration
- Added type to ebsconet pol schema
- Added logic to update paymentStatus and receiptStatus
- Manage new error code
- Added new unit tests
- Updated openapi-generator dependency to avoid security warning
Ideally all of the PRs involved in …
> [MODEBSNET-22] Support cancel pol

- pom.xml
- src/test/java/org/folio/ebsconet/OrdersControllerTest.java
- src/test/java/org/folio/ebsconet/OrdersServiceTest.java
https://issues.folio.org/browse/MODEBSNET-35
Update versions in pom and fix all related problems.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> MODEBSNET-35 - spring update

- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
- src/main/resources/swagger.api/schemas/mod-ebsconet/ebsconet_order_line.json
- src/test/java/org/folio/ebsconet/OrdersServiceTest.java
> [MODEBSNET-33]-updated schema

- pom.xml
https://issues.folio.org/browse/MODEBSNET-38
Remove dependency.
While it's helpful for …
> MODEBSNET-38 - remove org.json

- src/main/java/org/folio/ebsconet/client/NotesClient.java
- src/main/java/org/folio/ebsconet/service/NotesService.java
- src/main/java/org/folio/ebsconet/service/OrdersService.java
- src/test/java/org/folio/ebsconet/service/NotesServiceTest.java
> [MODEBSNET-33]-Updated NoteService

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODEBSNET-36
Morning Glory R2 2022 Release
> [MODEBSNET-36] Add release note for v1.3.0 Morning Glory R2 2022 Release

- descriptors/ModuleDescriptor-template.json
Major change in the NodeType was done:
Instead of **usage.noteTotal (Integer)** will be used **usage.isAssigned(Boolean)**
PR  : https://github.com/folio-org/mod-notes/pull/217/files
As we use only **nodeTypeCollection** without binding to schema and process response as JsonNode.
From JsonNode only "id" is interested part for us and "usage" is not involved, then bumping major version in the description will be enougph. 
- Are the …
> [MODEBSNET-40] - mod-notes interface version update

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
- src/main/java/org/folio/ebsconet/service/NotesService.java
- src/test/java/org/folio/ebsconet/OrdersServiceTest.java
https://issues.folio.org/browse/MODEBSNET-42
Release Morning Glory R2 2022 v1.3.2
> [MODEBSNET-42] Release Morning Glory R2 2022 v1.3.2

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODEBSNET-43
* added missed permission "finance.expense-classes.item.get"
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> MODEBSNET-43 added missed permission "finance.expense-classes.item.get"

- pom.xml
> [MODEBSNET-47] - Log4j version upgrade

- NEWS.md
- pom.xml
> [MODEBSNET-49] - Release 1.4.0

- pom.xml
- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
- src/test/java/org/folio/ebsconet/OrdersServiceTest.java
https://issues.folio.org/browse/MODEBSNET-53
* skip empty locations processing
While it's …
> MODEBSNET-53 skip empty locations processing

- NEWS.md
- pom.xml
While it's helpful for reviewers to help identify potential problems,
ensuring that it's safe …
> [MODEBSNET-55] - Release v2.0.0

- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
- Jenkinsfile
- README.md
- src/main/resources/swagger.api/ebsconet.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
> FOLIO-3678 MODEBSNET-61 Use GitHub Workflows api-lint and api-schema-lint and api-doc

- pom.xml
https://issues.folio.org/browse/MODEBSNET-64
updated spring folio base 7.0.0 to 7.2.0
While …
> [MODEBSNET-64] - Folio Spring base updated

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODEBSNET-63
While it's helpful for reviewers to help identify …
> [MODEBSNET-63] - Release v2.1.0

- src/main/java/org/folio/ebsconet/controller/OrdersController.java
- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
- src/test/java/org/folio/ebsconet/OrdersServiceTest.java
[MODEBSNET-66](https://issues.folio.org/browse/MODEBSNET-66) - Add possibility to work with empty vendorDetails object
especially as the number of inter-module and inter-team …
> [MODEBSNET-66] - Added possibility to work with empty vendorDetails

- NEWS.md
- pom.xml
- src/main/java/org/folio/ebsconet/controller/OrdersController.java
- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
- src/test/java/org/folio/ebsconet/OrdersServiceTest.java
While it's helpful for reviewers to help identify potential problems,
ensuring that it's safe …
> [MODEBSNET-66] - Release v2.1.1

- src/main/java/org/folio/ebsconet/service/NotesService.java
- src/test/java/org/folio/ebsconet/service/NotesServiceTest.java
https://issues.folio.org/browse/MODEBSNET-70
Throw ResourceNotFoundException in case if general note was not found.
especially as the number of inter-module and inter-team …
> [MODEBSNET-70] - Add error code if default note type "General note" is not exists

- pom.xml
https://folio-org.atlassian.net/browse/MODEBSNET-73 …
> [MODEBSNET-73] - mod-ebsconet: spring upgrade

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/MODEBSNET-74
> [MODEBSNET-74] - Release v2.2.0

- descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODFIN-358
> MODFIN-358. Update finance.funds interface

- descriptors/ModuleDescriptor-template.json
Verify notes permissions
https://folio-org.atlassian.net/browse/MODEBSNET-78
Update notes permissions
especially as the number of inter-module and inter-team dependencies …
> [MODEBSNET-78] - Update notes permissions

- pom.xml
[[MODEBSNET-83] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/MODEBSNET-83)
- Update versions
- Add module descriptor validator
> [MODEBSNET-83] Update libraries of dependant acq modules to the latest versions

- pom.xml
[[MODEBSNET-83] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/MODEBSNET-83)
- Add missing plugin repo
> [MODEBSNET-83] Add correct plugin repository

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/FOLIO-4102 …
> Release v2.3.0

- NEWS.md
- pom.xml
While it's helpful for reviewers to help identify potential problems,
ensuring that it's safe …
> Bug Fix Release v2.3.1

- Dockerfile
- Jenkinsfile
- pom.xml
- src/test/java/org/folio/ebsconet/OrdersControllerTest.java
[[FOLIO-4203] Update to mod-ebsconet Java 21](https://folio-org.atlassian.net/browse/FOLIO-4203)
Update java and dependency versions
> [FOLIO-4203] Update to mod-ebsconet Java 21

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/MODEBSNET-88 …
> Release v2.4.0

- src/main/java/org/folio/ebsconet/ModEbscoNetApplication.java
- src/main/java/org/folio/ebsconet/controller/OrdersController.java
- src/main/java/org/folio/ebsconet/controller/TenantController.java
- src/main/java/org/folio/ebsconet/controller/ValidationsController.java
- src/main/java/org/folio/ebsconet/mapper/OrdersMapper.java
- src/main/java/org/folio/ebsconet/models/MappingDataHolder.java
- src/main/java/org/folio/ebsconet/service/OrdersService.java
- src/test/java/org/folio/ebsconet/TestBase.java
- src/test/java/org/folio/ebsconet/TestSuite.java
- src/test/java/org/folio/ebsconet/controller/OrdersControllerTest.java
- src/test/java/org/folio/ebsconet/service/NotesServiceTest.java
- src/test/java/org/folio/ebsconet/service/OrdersServiceTest.java
- <https://folio-org.atlassian.net/browse/MODEBSNET-77>
- Add a new way to initiate the closing of purchase order via workflowStatus=Closed
- Update and clean feature classes and test classes by adding missing null checks, Closeable handling etc
- Update unit tests
> [MODEBSNET-77]. Update POL statuses when closing order as cancelled
